[package]
name = "marco_polo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
ignore = "0.4"
tree-sitter = "0.20"
tree-sitter-python = "0.20"
